modules/MubAdmin/modules/csvreader/models/XmlForm.php
<?php

use yii\base\Model;
namespace app\modules\MubAdmin\modules\csvreader\models;
use app\components\Model;
use app\helpers\HtmlHelper;

class XmlForm extends Model{
    public $file;
    
    public function rules(){
        return [
            [['file'],'required'],
            [['file'],'file','extensions'=>'xml','maxSize'=>1024 * 1024 * 10],
        ];
    }
    
    public function attributeLabels(){
        return [
            'file'=>'Select File',
        ];
    }
}

modules/MubAdmin/modules/csvreader/controllers/XmlController.php
<?php

namespace app\modules\MubAdmin\modules\csvreader\controllers;
use app\modules\MubAdmin\modules\csvreader\models\XmlForm;
use yii\web\Controller;
use yii\web\UploadedFile;
use app\helpers\StringHelper;
use app\modules\MubAdmin\modules\csvreader\models\Product;
use app\modules\MubAdmin\modules\csvreader\models\XmlProcess;
use app\modules\MubAdmin\modules\csvreader\models\FileUploaded;
use app\modules\MubAdmin\modules\csvreader\models\ProductBisac;
use \app\modules\MubAdmin\modules\csvreader\models\Bisac;
use Yii;
use DateTime;

class XmlController extends Controller
{
  public $layout = "@app/views/layouts/admin";
  /**
   * Renders the index view for the module
   * @return string
   */
  public function actionFileUpload()
  { 
    if(\Yii::$app->request->isAjax) {
    $model = new XmlForm();

    $xmlFile = UploadedFile::getInstance($model, 'file');

    $directory = \Yii::getAlias('@app/uploads') . DIRECTORY_SEPARATOR;
    if(!is_dir($directory)) {
        FileHelper::createDirectory($directory);
    }
    if($xmlFile) 
    {
      $uid = uniqid(time(), true);
      $fileName = $uid . '.' . $xmlFile->extension;
      $filePath = $directory . $fileName;
      if($xmlFile->saveAs($filePath))
      {
       $fileUploaded  = new FileUploaded();
       $fileUploaded->file_name = $uid . '.' . $xmlFile->extension;
       $fileUploaded->file_path = $filePath;
       $fileUploaded->load_status = '0';
       $mubUserId = \app\models\User::getMubUserId();
       $fileUploaded->mub_user_id = $mubUserId;
      if(!$fileUploaded->save())
      {
        p($fileUploaded->getErrors());
      }
      return true;
      }
    }
    return false;
    }
    else
    {
      return 'go away';
    }
  }

  public function actionChangeDataLoadStatus($id)
  {
    if(\Yii::$app->request->isAjax) 
    {
      $model = new FileUploaded();
      $nameId = explode('_',$id);
      $id2 = end($nameId);
      $file = $model::find()->where(['id' => $id2])->one();
      
      if($id == 'read_data_'.$id2)
      {
        $sql = Yii::$app->db->createCommand()->update('fileUpload', ['load_status' => 1], 'id = "'.$id2.'"')->execute();

         echo "<script>console.log('added ".$sql." records')</script>";
      }

      if($id == 'read_authors_'.$id2)
      {
        $sql = Yii::$app->db->createCommand()->update('fileUpload', ['load_status' => 2], 'id = "'.$id2.'"')->execute();

         echo "<script>console.log('added ".$sql." records')</script>";
      }

      if($id == 'read_publishers_'.$id2)
      {
        $sql = Yii::$app->db->createCommand()->update('fileUpload', ['load_status' => 3], 'id = "'.$id2.'"')->execute();

         echo "<script>console.log('added ".$sql." records')</script>";
      }

      if($id == 'link_publishers_'.$id2)
      {
        $sql = Yii::$app->db->createCommand()->update('fileUpload', ['load_status' => 4], 'id = "'.$id2.'"')->execute();

         echo "<script>console.log('added ".$sql." records')</script>";

      }

      if($id == 'link_authors_'.$id2)
      {
        $sql = Yii::$app->db->createCommand()->update('fileUpload', ['load_status' => 5], 'id = "'.$id2.'"')->execute();

         echo "<script>console.log('added ".$sql." records')</script>";

      }
    }
  }

  public function actionIndex()
  {
    $showFileUpload = new FileUploaded();
    $allFileUploaded = $showFileUpload::find()->all();
    return $this->render('index',['allFileUploaded' => $allFileUploaded]);
  }

  public function saveProductBisac($model)
  {
    $bisac = $model->bisac;
    $bisacId = Bisac::find()->where(['bisac_code' => $bisac])->one()->id;   
    $productBisacModel = new ProductBisac();
  }

  public function actionReadUploadedFile($id)
  {
    ini_set('max_execution_time', 200000);
    ini_set('memory_limit', '-1');
    $model = new XmlForm();
    $fileUploaded = new FileUploaded();
    $fileId = explode('_',$id)[2];
    $fileInstance = $fileUploaded::findOne($fileId);
    $path = $fileInstance->file_path;
    $model->file = $path;
    $z = new \XMLReader;
    $z->open($path);
    while ($z->read() && $z->name !== 'product');
    $i=0;

    $fields = '(`id`,`product_name`,`format`,`publish_date`,`slug`,`language`,`bisac`,`type`,`description`,`created_at`)';

    $i=1;
    while ($z->name === 'product')
    {
      try
      {
        $node = new \SimpleXMLElement($z->readOuterXML());
      }
      catch (Exception $e)
      {
        p([[$e],[$node]]);
      }
      //Skipp Empty Records
      if(((String)$node->title->b203 !== "")&&((String)$node->b064!=''))
      { 
      $title = (String) $node->title->b203;
      $pi = null;
      $ingProductId = null;
      foreach ($node->productidentifier as $key => $identifier) 
      {
          $pi[$key] = (Array) $identifier;
          if($pi[$key]['b221'] == '03')
          {
            $ingProductId = (String) $pi[$key]['b244'];    
          }
      }
      if(!$ingProductId)
      {
        p($pi);
      }
      $productName = str_replace("\n","",str_replace("'","\'",$title));
      $format = (String) $node->b012;
      $ts = (String) $node->b394[0]->attributes();
      $date = new DateTime("@$ts"); 
      $publishDate = $date->format('Y-m-d');
      $bisac = (String) $node->b064;
      $language = (String) $node->language->b252;
      $slug = StringHelper::generateSlug($title).'_'.$ingProductId."_".$language;
      $type = StringHelper::getFormatValue((String)$node->b012);
      $description = str_replace("\n","",str_replace("'","\'",strip_tags(str_replace("\\", "",(String)$node->othertext->d104)))); 
      $recordSet[$i] = [$ingProductId,$productName,$format,$publishDate,$slug,$language,$bisac,$type,$description];
      if($i%5000 == 0)
      {
        try
        {   
            $date = date('Y-m-d H:i:s');
            $loop = 1;
            $values = "";
            foreach ($recordSet as $record) 
            {
              $record[] = $date;
              $values .= "('".implode("','",$record)."')";
              if($loop !== 5000)
              {
                $values .= ",";
              }
              $loop++;
            }
          $command = "INSERT INTO `product` ".$fields." VALUES ".$values." ON DUPLICATE KEY UPDATE `id`=`id`,`product_name`=`product_name`,`format`=`format`,`publish_date`=`publish_date`,`slug`=`slug`,`language`=`language`,`bisac`=`bisac`,`type`=`type`,`description`=`description`,`created_at`=`created_at`";
          $sql = \Yii::$app->db->createCommand($command)->execute();       
          $recordSet = [];
        }
        catch (Exception $e)
        {
            p([['exception' => $e],['at' => $i]]);
        }
        echo "<script>console.log(".$sql." records inserted)</script>";
        sleep(2); 
      }
      $i++;
    }
      $z->next('product');
    }
    if(!empty($recordSet))
    {
      try{
            $date = date('Y-m-d H:i:s');
            $loop = 1;
            $count = count($recordSet);
            $values = "";
            foreach ($recordSet as $record) 
            {
              $record[] = $date;
              $values .= "('".implode("','",$record)."')";
              if($loop !== $count)
              {
                $values .= ",";
              }
              $loop++;
            }
         $command = "INSERT INTO `product` ".$fields." VALUES ".$values." ON DUPLICATE KEY UPDATE `id`=`id`,`product_name`=`product_name`,`format`=`format`,`publish_date`=`publish_date`,`slug`=`slug`,`language`=`language`,`bisac`=`bisac`,`type`=`type`,`description`=`description`,`created_at`=`created_at`";
        $sql = \Yii::$app->db->createCommand($command)->execute();
        }
        catch (Exception $e){
          p([['exception' => $e],['at' => $i]]);
        }
        $this->redirect(['/mub-admin/csvreader/xml?product=read_authors_'.$fileId]);
    }
  }

  public function actionTest()
  {
    ini_set('max_execution_time', 200000);
    ini_set('memory_limit', '-1');
    $sql = "select ing_product_id from `publisher_products` where 1 limit 100";
    $sqlCommand = \Yii::$app->db->createCommand($sql);
    $allPublisher = $sqlCommand->queryAll();
    $price = [];
    foreach ($allPublisher as $key => $value) 
    {
      $sql = 'select * from `price` where `ean_13` = "'.$value["ing_product_id"].'";';
      $sqlCommand = \Yii::$app->db->createCommand($sql);
      $price[] = $sqlCommand->queryAll();
    }
    p($price);
  }

  public function actionLinkAuthors($id)
  {
    ini_set('max_execution_time', 200000);
    ini_set('memory_limit', '-1');
    $model = new XmlForm();
    $fileUploaded = new FileUploaded();
    $fileId = explode('_',$id)[2];
    $fileInstance = $fileUploaded::findOne($fileId);
    $path = $fileInstance->file_path;
    $model->file = $path;
    // $xmlProcess = new app\modules\MubAdmin\modules\csvreader\models\XmlProcess;
    $z = new \XMLReader;
    $z->open($path);
    while ($z->read() && $z->name !== 'product');
    $i = 1;
    while ($z->name === 'product')
    {
      try
      {
        $node = new \SimpleXMLElement($z->readOuterXML());
      }
      catch (Exception $e)
      {
        p([[$e],[$node]]);
      }
      //get Current Book Title
      if(((String)$node->title->b203 !== "") && ((String)$node->b064!=''))
      { 
      $title = (String) $node->title->b203;
      //getting product EAN13
      $pi = null;
      $ingProductId = null;
      foreach ($node->productidentifier as $key => $identifier) 
      {
          $pi[$key] = (Array) $identifier;
          if($pi[$key]['b221'] == '03')
          {
            $ingProductId = (String) $pi[$key]['b244'];      
          }
      }
      if(!$ingProductId)
      {
        p($pi);
      }
      //Getting Author details
      $contributor = (Array) $node->contributor;
      $arrayValues = array_values($contributor);
      if(in_array('A01', $arrayValues))
      {
        $name = Null;
        $keyName = Null;
        $lastName = Null;
        $salutation = Null;
        foreach($contributor as $contKey => $contValue)
        {

modules/MubAdmin/modules/csvreader/views/xml/index.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
// use dosamigos\fileupload\FileUploadUI;
// use app\helpers\ImageUploader;
// use dosamigos\tinymce\TinyMce;
use limion\jqueryfileupload\JQueryFileUpload;
use app\modules\MubAdmin\modules\csvreader\models\XmlForm;
$xmlForm = new XmlForm();

?>
<div class="property-form">

    <?php $form = ActiveForm::begin(); ?>
    <h3>Product Upload</h3>
        <?= JQueryFileUpload::widget([
            'model' => $xmlForm,
            'attribute' => 'file',
            'url' => ['xml/file-upload'],
            'appearance'=>'ui', 
            'gallery'=>false, 
            'formId'=>$form->id,
            'options' => [
                'accept' => 'xml/*'
            ],
            'clientOptions' => [
                'maxFileSize' => 3000000000,
                'dataType' => 'json',
                'autoUpload'=>false
            ]
        ]);
    ?>
    <?php ActiveForm::end(); ?>

</div>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_content">
        <div class="table-responsive">
            <table class="table table-striped jambo_table bulk_action">
                <thead>
                    <tr class="headings">
                    <th>
                      <div class="icheckbox_flat-green" style="position: relative;"><input type="checkbox" id="check-all" class="flat" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div>
                    </th>
                    <th class="column-title">Id</th>
                    <th class="column-title">File Name</th>
                    <th class="column-title">File Path</th>
                    <th class="column-title no-link last"><span class="nobr">Action</span>
                    </th>
                    <th class="bulk-actions" colspan="7">
                      <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                    </th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($allFileUploaded as $value) { 
                 $newstring = substr($value['file_name'], -3);
                    if($newstring == 'xml'){ ?>

                  <tr class="even pointer">
                    <td class="a-center ">
                      <div class="icheckbox_flat-green" style="position: relative;"><input type="checkbox" class="flat" name="table_records" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div>
                    </td>
                    <td class=" "><?= $value['id']; ?></td>
                    <td class=" "><?= $value['file_name']; ?></td>
                    <td class=" "><?= $value['file_path']; ?></td>
                    
                    <?php if($value['load_status'] == '0'){?>
                    <td class="last">
                        <button type="button" id="read_data_<?= $value['id']; ?>" class="btn btn-round btn-primary read_data">
                            Read Products
                        </button>
                    </td>
                    <?php }?>
                    <?php if($value['load_status'] == '1'){?>
                    <td class="last">
                        <button type="button" id="read_authors_<?= $value['id']; ?>" class="btn btn-round btn-success authors_read">
                            Read Authors
                        </button>
                    </td>
                    <?php }?>
                    <?php if($value['load_status'] == '2'){?>
                    <td class="last">
                        <button type="button" id="read_publishers_<?= $value['id']; ?>" class="btn btn-round btn-danger publishers_read">
                            Read Publishers
                        </button>
                    </td>
                    <?php }?>
                    <?php if($value['load_status'] == '3'){?>
                     <td class="last">
                        <button type="button" id="link_publishers_<?= $value['id']; ?>" class="btn btn-round btn-primary publishers_link">
                            Link Publishers
                        </button>
                    </td>
                    <?php }?>
                    <?php if($value['load_status'] == '4'){?>
                     <td class="last">
                        <button type="button" id="link_authors_<?= $value['id']; ?>" class="btn btn-round btn-success authors_link">
                            Link Authors
                        </button>
                    </td>
                    <?php }?>
                    <?php if($value['load_status'] == '5'){?>
                     <td class="last">
                        <button type="button" id="all_update_<?= $value['id']; ?>" class="btn btn-round btn-success ">
                            All Updated
                        </button>
                    </td>
                    <?php }?>
                  </tr>
                <?php } } ?>
                </tbody>
            </table>
        </div>
      </div>
    </div>
</div>


<div class="property-form" style="margin-top: 13em;">
    <h3>Product Price Upload</h3>
        <?php $form = ActiveForm::begin(); ?>
            <?= JQueryFileUpload::widget([
            'model' => $xmlForm,
            'attribute' => 'file',
            'url' => ['xml/file-upload'],
            'appearance'=>'ui', 
            'gallery'=>false, 
            'formId'=>$form->id,
            'options' => [
                'accept' => 'dat/*'
            ],
            'clientOptions' => [
                'maxFileSize' => 3000000000,
                'dataType' => 'json',
                'autoUpload'=>false
            ]
            ]);?>
        <?php ActiveForm::end(); ?>
</div>
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_content">
        <div class="table-responsive">
            <table class="table table-striped jambo_table bulk_action">
                <thead>
                    <tr class="headings">
                    <th>
                      <div class="icheckbox_flat-green" style="position: relative;"><input type="checkbox" id="check-all" class="flat" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div>
                    </th>
                    <th class="column-title">User Id</th>
                    <th class="column-title">File Name</th>
                    <th class="column-title">File Path</th>
                    <th class="column-title no-link last"><span class="nobr">Action</span>
                    </th>
                    <th class="bulk-actions" colspan="7">
                      <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                    </th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($allFileUploaded as $value) { 
                $newstring = substr($value['file_name'], -3);
                if($newstring == 'dat'){?>
                  <tr class="even pointer">
                    <td class="a-center ">
                      <div class="icheckbox_flat-green" style="position: relative;"><input type="checkbox" class="flat" name="table_records" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div>
                    </td>
                    <td class=" "><?= $value['id']; ?></td>
                    <td class=" "><?= $value['file_name']; ?></td>
                    <td class=" "><?= $value['file_path']; ?></td>

                    <td class="last">
                        <button type="button" id="read_price_<?= $value['id']; ?>" class="btn btn-round btn-primary read_price">
                            Read Price
                        </button>
                       
                    </td>
                    <?php } } ?>
                </tbody>
            </table>
        </div>
      </div>
    </div>
</div>
<?php if(\Yii::$app->request->getQueryParam('price') || \Yii::$app->request->getQueryParam('product')){
$this->registerJsFile('/js/automation.js',['depends' => [\yii\web\JqueryAsset::className()]]);
 }?>